---
sidebar: sidebar 
permalink: storagegrid-enable.html 
keywords: storagegrid, how to enable, third-party solutions, tools, applications, examples 
summary: Saiba como testar e habilitar aplicativos em seu ambiente StorageGRID. 
---
= Soluções e recursos do StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vá para https://docs.netapp.com/us-en/storagegrid-enable/index.html["Soluções e recursos do StorageGRID"^] para aprender como testar e habilitar aplicativos em seu ambiente StorageGRID .

* Soluções e recursos do StorageGRID * fornecem exemplos e livros de receitas que expandem a documentação do produto neste site e descrevem algumas próximas etapas na avaliação e integração com o StorageGRID.

Algumas das informações incluem:

* Listas de soluções de terceiros validadas para versões anteriores e atuais do StorageGRID.
* Guias de recursos do produto. Por exemplo, esses guias fornecem todas as informações necessárias para criar pools de armazenamento em nuvem.
* Guias de ferramentas e aplicações.
* Exemplos de API para usar recursos do StorageGRID, como criptografia S3 e bloqueio de objetos S3.

