---
sidebar: sidebar 
permalink: whats-new-appliances.html 
keywords: storagegrid, appliance, whats new 
summary: Saiba o que há de novo neste site de documentação. 
---
= O que há de novo para eletrodomésticos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba o que há de novo para os dispositivos StorageGRID.



== Aparelhos SG5812 e SG5860

Os novos dispositivos StorageGRID SG5812 e SG5860 são plataformas integradas de storage e computação que operam como nós de storage em uma grade StorageGRID. Consulte https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg5800.html["Aparelhos SG5800: Visão geral"] para saber mais.



== SG6160 aparelho

O novo dispositivo StorageGRID SG6160 inclui uma controladora de computação e um compartimento de controladora de storage que contém duas controladoras de storage e 60 unidades, bem como duas unidades SSD NVMe para armazenamento em cache. Opcionalmente, é possível adicionar gavetas de expansão de 60 unidades ao SG6160. link:installconfig/hardware-description-sg6100.html["Aparelhos SGF6100: Visão geral"]Consulte para saber mais.



== Aparelhos de serviços SG110 e SG1100

Os novos dispositivos de serviços StorageGRID SG110 e SG1100 são uma atualização de hardware evolutiva que fornece desempenho administrativo e de balanceamento de carga aprimorado. link:./installconfig/hardware-description-sg110-and-1100.html["Dispositivo de serviços SG110 e SG1100: Visão geral"]Consulte .
