---
sidebar: sidebar 
permalink: whats-new-appliances.html 
keywords: storagegrid, appliance, whats new 
summary: Saiba o que há de novo neste site de documentação. 
---
= Novidades nos dispositivos StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba o que há de novo nos dispositivos StorageGRID .



== A rede do cliente pode ser configurada sem um endereço IP

Agora você pode habilitar a Rede do Cliente sem especificar um endereço IP.  Isso permite que a rede do cliente tenha interfaces VLAN configuradas no StorageGRID sem exigir um endereço IP extra para a própria interface. Consulte link:.//installconfig/setting-ip-configuration.html["Configurar endereços IP do StorageGRID"] .



== Números de versão do software StorageGRID e do Appliance Installer alinhados

Com o StorgeGRID versão 12.0, o número da versão do StorageGRID Appliance Installer corresponde à versão do software StorageGRID .  Os usuários não precisam mais descobrir quais versões funcionam juntas. Consulte link:./installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["Verifique e atualize a versão do instalador do StorageGRID Appliance"] .



== Informações sobre o BMC

Informações detalhadas sobre o uso da interface BMC do dispositivo StorageGRID agora estão disponíveis. Consulte link:./commonhardware/use-bmc.html["Use o controlador de gerenciamento de placa base (BMC) do StorageGRID Appliance"] .



== Aparelhos SG5812 e SG5860

Os dispositivos StorageGRID SG5812 e SG5860 são plataformas integradas de armazenamento e computação que operam como nós de armazenamento em uma grade StorageGRID .  Consulte olink:./installconfig/hardware-description-sg5800.html["Aparelhos SG5800: Visão geral"] para saber mais.



== SG6160 aparelho

O novo dispositivo StorageGRID SG6160 inclui um controlador de computação e uma prateleira de controlador de armazenamento que contém dois controladores de armazenamento e 60 unidades, bem como duas unidades SSD NVMe para armazenamento em cache.  Opcionalmente, prateleiras de expansão de 60 unidades podem ser adicionadas ao SG6160.  Consultelink:./installconfig/hardware-description-sg6100.html["Aparelhos SGF6100: Visão geral"] para saber mais.



== Aparelhos de serviços SG110 e SG1100

Os novos dispositivos de serviços StorageGRID SG110 e SG1100 são uma atualização de hardware evolutiva que oferece melhor desempenho administrativo e de balanceamento de carga. Consulte link:./installconfig/hardware-description-sg110-and-1100.html["Dispositivo de serviços SG110 e SG1100: Visão geral"] .
