---
permalink: sg6200/reinstalling-sg6200-cover.html 
sidebar: sidebar 
keywords: storagegrid, sg6200, sgf6212, storage node, storage appliance, cover, install, installing, installation, reinstall, reinstalling, reinstallation 
summary: Retire a tampa do aparelho para aceder aos componentes internos para manutenção e volte a colocar a tampa quando terminar. 
---
= Substitua a tampa SGF6212 ou SG6200-CN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Retire a tampa do aparelho para aceder aos componentes internos para manutenção e volte a colocar a tampa quando terminar.



== Passo 1: Remova a tampa

.Passos
. Enrole a extremidade da correia de uma pulseira ESD à volta do pulso e fixe a extremidade do clipe a um solo metálico para evitar descargas estáticas ao trabalhar no interior do aparelho.
. link:reinstalling-sg6200-into-cabinet-or-rack.html["Retire o aparelho do armário ou do rack"] para acessar a tampa superior.


. Destrave a trava da tampa pressionando o botão azul de trava na tampa do appliance.
+
image:../media/drw_s2025_cover_replace_ieops-2559.svg["Destravando e removendo a tampa do aparelho"]

. Rode o trinco para cima e para trás em direção à parte traseira do chassis do aparelho até parar; em seguida, levante cuidadosamente a tampa do chassis e coloque-a de lado.




== Passo 2: reinstale a tampa

.Passos
. Com a trava da tampa aberta, alinhe a tampa acima do chassi e abaixe-a cuidadosamente.
. Rode o trinco da tampa para a frente e para baixo até parar e a tampa assentar totalmente no chassis. Verifique se não existem folgas ao longo da extremidade dianteira da tampa.
+
Se a tampa não estiver totalmente encaixada, poderá não conseguir deslizar o aparelho para dentro do rack.

. link:reinstalling-sg6200-into-cabinet-or-rack.html["Volte a instalar o aparelho no armário ou no rack"].

