---
permalink: installconfig/automating-configuration-of-storagegrid.html 
sidebar: sidebar 
keywords: automate, automating, automation, automatic, configuration, configure 
summary: Depois de instalar e configurar os nós de grade, você pode automatizar a configuração do sistema StorageGRID. 
---
= Automatizar a configuração do StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de instalar e configurar os nós de grade, você pode automatizar a configuração do sistema StorageGRID.

.Antes de começar
* Você sabe a localização dos seguintes arquivos do arquivo de instalação.
+
[cols="1a,1a"]
|===
| Nome do ficheiro | Descrição 


| configure-StorageGRID.py  a| 
Script Python usado para automatizar a configuração



| configure-StorageGRID.sample.json  a| 
Exemplo de arquivo de configuração para uso com o script



| configure-StorageGRID.blank.json  a| 
Arquivo de configuração em branco para uso com o script

|===
* Criou um `configure-storagegrid.json` ficheiro de configuração. Para criar este ficheiro, pode modificar o ficheiro de configuração de exemplo (`configure-storagegrid.sample.json`) ou o ficheiro de configuração em branco (`configure-storagegrid.blank.json`).


.Sobre esta tarefa
Você pode usar o `configure-storagegrid.py` script Python e o `configure-storagegrid.json` arquivo de configuração para automatizar a configuração do seu sistema StorageGRID.


NOTE: Também pode configurar o sistema utilizando a https://docs.netapp.com/us-en/storagegrid-118/primer/exploring-grid-manager.html["Gerenciador de grade"^] ou a link:overview-of-installation-rest-apis.html["API de instalação"].

.Passos
. Faça login na máquina Linux que você está usando para executar o script Python.
. Mude para o diretório onde você extraiu o arquivo de instalação.
+
Por exemplo
`cd StorageGRID-Webscale-_version/platform_`

+
 `_platform_`onde está `debs`, `rpms`, `vsphere` ou .

. Execute o script Python e use o arquivo de configuração que você criou.
+
Por exemplo:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Depois de terminar
Um arquivo do Pacote de recuperação `.zip` é gerado durante o processo de configuração e é baixado para o diretório onde você está executando o processo de instalação e configuração. Você deve fazer backup do arquivo do pacote de recuperação para que você possa recuperar o sistema StorageGRID se um ou mais nós de grade falhar. Por exemplo, copie-o para um local de rede seguro e de backup e para um local seguro de armazenamento em nuvem.


CAUTION: O arquivo do pacote de recuperação deve ser protegido porque contém chaves de criptografia e senhas que podem ser usadas para obter dados do sistema StorageGRID.

Se você especificou que senhas aleatórias devem ser geradas, você precisa extrair o `Passwords.txt` arquivo e procurar as senhas necessárias para acessar seu sistema StorageGRID.

[listing]
----
######################################################################
##### The StorageGRID "recovery package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
O sistema StorageGRID é instalado e configurado quando é apresentada uma mensagem de confirmação.

[listing]
----
StorageGRID has been configured and installed.
----