---
permalink: installconfig/changing-root-password-for-bmc-interface.html 
sidebar: sidebar 
keywords: BMC, baseboard management controller, password, login, credential, credentials 
summary: Para segurança, você deve alterar a senha do administrador ou usuário root do BMC. 
---
= Altere a senha de administrador ou raiz para a interface do BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para segurança, você deve alterar a senha do administrador ou usuário root do BMC.

.Antes de começar
O cliente de gerenciamento está usando um https://docs.netapp.com/us-en/storagegrid/admin/web-browser-requirements.html["navegador da web suportado"^].

.Sobre esta tarefa
Quando você instala o dispositivo pela primeira vez, o BMC usa uma senha padrão para o administrador ou usuário raiz. Você deve alterar a senha do administrador ou usuário raiz para proteger seu sistema.

O usuário padrão depende de quando você instalou o dispositivo StorageGRID. O usuário padrão é *admin* para novas instalações e *root* para instalações mais antigas.

.Passos
. No cliente, insira o URL do instalador do StorageGRID Appliance:
+
`*https://_Appliance_IP_:8443*`

+
Para `_Appliance_IP_`, use o endereço IP do dispositivo em qualquer rede StorageGRID.

+
A página inicial do instalador do dispositivo StorageGRID é exibida.

. Selecione *Configurar hardware* > *Configuração do BMC*.
+
É apresentada a página Baseboard Management Controller Configuration (Configuração do controlador de gestão de base).

. Insira uma nova senha para a conta de administrador ou raiz nos dois campos fornecidos.
. Selecione *Guardar*.

