---
permalink: installconfig/configuring-snmp-settings-for-bmc.html 
sidebar: sidebar 
keywords: SNMP, configure, setup, set up 
summary: Se estiver familiarizado com a configuração do SNMP para hardware, pode utilizar a interface BMC para configurar as definições SNMP para os dispositivos SG6100, SG6000 e serviços. Você pode fornecer strings de comunidade seguras, ativar Trap SNMP e especificar até cinco destinos SNMP. 
---
= Configure as definições SNMP para BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se estiver familiarizado com a configuração do SNMP para hardware, pode utilizar a interface BMC para configurar as definições SNMP para os dispositivos SG6100, SG6000 e serviços. Você pode fornecer strings de comunidade seguras, ativar Trap SNMP e especificar até cinco destinos SNMP.

[role="tabbed-block"]
====
.SG110, SG1100, SG6100-CN, SGF6112
--
.Antes de começar
* Você sabe como link:../installconfig/accessing-bmc-interface.html["Acesse o painel do BMC"].
* Tem experiência em configurar definições SNMP para equipamento SNMPv3.



NOTE: As definições do BMC efetuadas por este procedimento poderão não ser preservadas se o aparelho falhar e tiver de ser substituído. Certifique-se de que tem um registo de todas as definições aplicadas, para que possam ser facilmente reaplicadas após uma substituição de hardware, se necessário.

Estas instruções mostram a versão mais recente do firmware BMC disponível para alguns dispositivos StorageGRID. O seu dispositivo StorageGRID pode ter uma versão de firmware BMC ligeiramente diferente.

* A versão mais recente do firmware BMC suporta apenas SNMPv3.
* O firmware do BMC é atualizado durante as atualizações de software do StorageGRID. Se não estiver a executar a versão mais recente do software StorageGRID, pode atualizar o dispositivo para a versão mais recente do StorageGRID para instalar o https://docs.netapp.com/us-en/storagegrid/upgrade/how-your-system-is-affected-during-upgrade.html#appliance-firmware-is-upgraded["Versão de firmware BMC mais recente disponível para o seu aparelho"].
* Se o BMC for diferente antes ou depois de uma atualização do StorageGRID:
+
** Consulte as instruções no separador SG100, SG1000, SG6000-CN.
** link:../commonhardware/use-bmc.html["Use o StorageGRID BMC"] Também pode ter informações para ajudá-lo a adaptar estas instruções para a sua versão do BMC.




.Passos
. Configurar traps SNMP como um ou mais destinos de LAN.
+
.. No painel do BMC, selecione *Configurações* > *filtros de evento da plataforma* > *Destinos da LAN*.
.. Para tipo de destino, selecione *SNMP Trap*.
.. Para Endereço de destino SNMP, introduza o endereço IP de destino.
+

NOTE: Utilize um endereço IP para o Endereço de destino SNMP. Nomes DNS não são suportados.

.. Selecione *Guardar*.


. Se você estiver usando traps SNMP para entregar notificações de alerta, consulte a seção filtros de evento da Plataforma do https://kb.netapp.com/hybrid/StorageGRID/Platforms/How_to_use_StorageGRID_Appliance_BMC_with_vendor_supplied_user_guide["Manual do utilizador do BMC"^] para obter informações sobre como usar o BMC para configurar políticas de alerta e filtros de evento.
. (Opcional) Ativar e configurar SNMP para um utilizador BMC.
+
.. No painel do BMC, selecione *Configurações* > *Gerenciamento de usuários*; em seguida, selecione um usuário do BMC.
.. Consulte a secção Gestão de utilizadores da https://kb.netapp.com/hybrid/StorageGRID/Platforms/How_to_use_StorageGRID_Appliance_BMC_with_vendor_supplied_user_guide["Manual do utilizador do BMC"^] para obter informações sobre a configuração das definições SNMP para um utilizador BMC.




--
.SG100, SG1000, SG6000-CN
--
.Antes de começar
* Você sabe como link:../installconfig/accessing-bmc-interface.html["Acesse o painel do BMC"].
* Tem experiência em configurar definições SNMP para equipamento SNMPv1-v2c.



NOTE: As definições do BMC efetuadas por este procedimento poderão não ser preservadas se o aparelho falhar e tiver de ser substituído. Certifique-se de que tem um registo de todas as definições aplicadas, para que possam ser facilmente reaplicadas após uma substituição de hardware, se necessário.

.Passos
. No painel BMC, selecione *Configurações* > *Configurações SNMP*.
. Na página Configurações SNMP, selecione *Ativar SNMP V1/V2* e, em seguida, forneça uma String comunitária somente leitura e uma String Comunidade de leitura-escrita.
+
A String da Comunidade somente leitura é como uma ID de usuário ou senha. Você deve alterar esse valor para evitar que intrusos obtenham informações sobre a configuração da rede. A cadeia de Comunidade de leitura-escrita protege o dispositivo contra alterações não autorizadas.

. Opcionalmente, selecione *Ativar Trap* e insira as informações necessárias.
+

NOTE: Introduza o IP de destino para cada trap SNMP utilizando um endereço IP. Nomes DNS não são suportados.

+
Ative traps se quiser que o aparelho envie notificações imediatas para um console SNMP quando ele estiver em um estado incomum. Dependendo do dispositivo, os traps podem indicar falhas de hardware de vários componentes, condições de ligação para cima/para baixo, limites de temperatura excedidos ou tráfego elevado.

. Opcionalmente, clique em *Send Test Trap* para testar suas configurações.
. Se as configurações estiverem corretas, clique em *Salvar*.


--
====