---
permalink: installconfig/configuring-hardware.html 
sidebar: sidebar 
keywords: storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: Depois de aplicar energia ao aparelho, você configura as conexões de rede que serão usadas pelo StorageGRID. 
---
= Configurar hardware: Visão geral
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de aplicar energia ao aparelho, você configura as conexões de rede que serão usadas pelo StorageGRID.



== Configure as conexões de rede necessárias

Para todos os dispositivos, você executa várias tarefas para configurar as conexões de rede necessárias, como:

* Acesse o instalador do dispositivo
* Configurar ligações de rede
* Verifique as conexões de rede no nível da porta




== Configuração adicional que pode ser necessária

Dependendo de quais tipos de appliance você está configurando, pode ser necessária uma configuração de hardware adicional.



=== Gerente do sistema da SANtricity

Para SG6160, SG6000, SG5800 e SG5700, você configura o Gerenciador de sistema do SANtricity. O software SANtricity é usado para monitorar o hardware desses dispositivos.



=== Interface BMC

Os seguintes dispositivos têm uma interface BMC que deve ser configurada:

* SG100
* SG110
* SG1000
* SG1100
* SG6000
* SG6100




== Configuração opcional

* Dispositivos de storage
+
** Configure o Gerenciador de sistema do SANtricity (SG5700, SG5800, SG6000 e SG6100) o software que você usará para monitorar o hardware
** Altere o modo RAID
** Aceder à interface BMC para o controlador SG6000-CN ou SG6100-CN


* Aparelhos de serviços
+
** Acesse a interface BMC para o SG100, SG110, SG1000 e SG1100



