---
permalink: installconfig/configuring-hardware.html 
sidebar: sidebar 
keywords: storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: Depois de aplicar energia ao aparelho, você configura as conexões de rede que serão usadas pelo StorageGRID. 
---
= Configurar o hardware do dispositivo StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de aplicar energia ao aparelho, você configura as conexões de rede que serão usadas pelo StorageGRID.



== Configurações de hardware necessárias



=== Conexões de rede

Você deve configurar e verificar as conexões de rede necessárias para todos os dispositivos:

* link:../installconfig/accessing-storagegrid-appliance-installer.html["Acesse o instalador do dispositivo"]
* link:../installconfig/configuring-network-links.html["Configurar ligações de rede"]
* link:../installconfig/verifying-port-level-network-connections.html["Verifique as conexões de rede no nível da porta"]




=== Interface BMC

Você deve link:../installconfig/configuring-bmc-interface.html["configurar a interface do BMC"] se estiver instalando um dos seguintes dispositivos:

* SG100
* SG110
* SG120
* SG1000
* SG1100
* SG1200
* SGF6024
* SGF6112
* SGF6212
* SG6060
* SG6160
* SG6260


Você pode usar a interface BMC para configurar SNMP e outras configurações de baixo nível para seus dispositivos. Ela também permite solucionar problemas na instalação do hardware, determinar o estado de energia do seu dispositivo e controlar o LED de identificação do seu dispositivo.

Para saber mais sobre os recursos que você pode usar com o BMC, consulte link:../commonhardware/use-bmc.html["Use a interface BMC"].



== Configurações de hardware opcionais



=== Gerente do sistema da SANtricity

Você pode link:../installconfig/accessing-and-configuring-santricity-system-manager.html["configurar SANtricity System Manager"] se tiver um dos seguintes dispositivos:

* SG5712
* SG5760
* SG5812
* SG5860
* SGF6024
* SG6060
* SG6160
* SG6260


O software SANtricity System Manager permite que você:

* Monitore os dados de desempenho do sistema, o status dos componentes de hardware e as funções de suporte do seu dispositivo
* Gerencie chaves de segurança de unidades, alertas SNMP e syslog e senhas de administrador para acessar SANtricity System Manager
* Configurar acesso à E-Series AutoSupport




=== Habilite a criptografia de nó ou unidade

Você pode link:../installconfig/optional-enabling-node-encryption.html["Ativar criptografia de nó ou unidade"] proteger as unidades e os discos do seu dispositivo.



=== Alterar modo RAID

Você pode link:../installconfig/optional-changing-raid-mode.html["Altere o modo RAID do seu dispositivo de storage"] adequar isso às suas necessidades de armazenamento e recuperação.

Os seguintes dispositivos suportam a alteração do modo RAID:

* SG5760
* SG5860
* SGF6024
* SG6060
* SG6160
* SG6260




=== Remapear portas de rede

Você pode link:../installconfig/optional-remapping-network-ports-for-appliance.html["Remapeie as portas de rede do seu dispositivo"] otimizar suas conexões de rede.
