---
permalink: sg6100/upgrading-santricity-os-on-storage-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5800, storage node, storage appliance, controller, storage controller, upgrade, upgrading, SANtricity OS, SANtricity 
summary: Para garantir o funcionamento ideal do controlador de storage, é necessário atualizar para a versão de manutenção mais recente do SANtricity os qualificado para o seu dispositivo StorageGRID. 
---
= Atualizar o SANtricity os no controlador de storage SG6160
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para garantir o funcionamento ideal do controlador de storage, é necessário atualizar para a versão de manutenção mais recente do SANtricity os qualificado para o seu dispositivo StorageGRID.

Determine a versão mais recente do sistema operacional SANtricity que foi qualificada para uso no seu dispositivo StorageGRID consultando https://mysupport.netapp.com/site/products/all/details/storagegrid-appliance/downloads-tab["Downloads do NetApp: StorageGRID Appliance"] e baixando-a, se necessário.

Transfira o novo ficheiro de software do sistema operativo SANtricity a partir https://mysupport.netapp.com/site/products/all/details/storagegrid-appliance/downloads-tab["Downloads do NetApp: StorageGRID Appliance"^]do .

Use um dos seguintes procedimentos com base na versão do SANtricity os atualmente instalado:

* Você pode usar o Gerenciador de Grade para executar a atualização.
+
link:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5800.html["Atualize o SANtricity os em controladores de storage usando o Gerenciador de Grade"]

* Pode utilizar o modo de manutenção para efetuar a atualização.
+
link:upgrading-santricity-os-on-e4000-controller-using-maintenance-mode.html["Atualize o SANtricity os no controlador E4000 usando o modo de manutenção"]

+

NOTE: Para controladores de storage que atualmente usam o SANtricity os mais recente que o 08.42.20.00 (11,42), recomenda-se a link:upgrading-santricity-os-on-storage-controllers-using-grid-manager-sg5800.html["Use o Gerenciador de Grade para aplicar uma atualização"]. No entanto, pode utilizar o procedimento de modo de manutenção se preferir ou tiver sido instruído a fazê-lo através da assistência técnica.


