---
permalink: sg5700/replacing-e5700sg-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, Replacing, replace, E5700sg, controller, remove, removing, removal, install, installing, installation 
summary: Talvez seja necessário substituir o controlador E5700SG se ele não estiver funcionando de forma ideal ou se ele tiver falhado. 
---
= Substitua o controlador de computação E5700SG
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Talvez seja necessário substituir o controlador E5700SG se ele não estiver funcionando de forma ideal ou se ele tiver falhado.

.Antes de começar
* Você tem um controlador de substituição com o mesmo número de peça do controlador que está substituindo.
* Você baixou as instruções do e-Series para substituir um controlador E5700 com falha.
+

NOTE: Use as instruções do e-Series para referência somente se você precisar de mais detalhes para executar uma etapa específica. Não confie nas instruções da série e para substituir um controlador no dispositivo StorageGRID, porque os procedimentos não são os mesmos. Por exemplo, as instruções do e-Series para o controlador E5700 descrevem como remover a bateria e a placa de interface do host (HIC) de um controlador com falha e instalá-los em um controlador de substituição. Estas etapas não se aplicam ao controlador E5700SG.

* Você tem etiquetas para identificar cada cabo conetado ao controlador.


.Sobre esta tarefa
O nó de storage do dispositivo não estará acessível quando você substituir o controlador. Se o controlador E5700SG estiver a funcionar o suficiente, pode efetuar um encerramento controlado no início deste procedimento.


NOTE: Se você estiver substituindo o controlador antes de instalar o software StorageGRID, talvez você não consiga acessar o instalador do StorageGRID Appliance imediatamente após concluir este procedimento. Embora você possa acessar o Instalador de dispositivos StorageGRID de outros hosts na mesma sub-rede que o appliance, você não pode acessá-lo de hosts em outras sub-redes. Esta condição deve resolver-se dentro de 15 minutos (quando qualquer entrada de cache ARP para o tempo limite do controlador original), ou você pode limpar a condição imediatamente, limpando quaisquer entradas de cache ARP antigas manualmente do roteador ou gateway local.

.Passos
. Desligue o controlador E5700SG.
+
.. Faça login no nó da grade:
+
... Introduza o seguinte comando: `ssh admin@_grid_node_IP_`
... Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
... Digite o seguinte comando para mudar para root: `su -`
... Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.



.. Desligue o controlador E5700SG
`*shutdown -h now*`
.. Aguarde até que quaisquer dados na memória cache sejam gravados nas unidades.
+
O LED verde Cache ative na parte de trás do controlador E2800 fica aceso quando os dados em cache precisam ser gravados nas unidades. Tem de esperar que este LED se desligue.



. Desligue a alimentação.
+
.. Na página inicial do Gerenciador do sistema do SANtricity, selecione *Exibir operações em andamento*.
.. Confirme se todas as operações foram concluídas.
.. Desligue ambos os interrutores de alimentação do aparelho.
.. Aguarde que todos os LEDs se desliguem.


. Se as redes StorageGRID conetadas ao controlador usarem servidores DHCP:
+
.. Observe os endereços MAC das portas no controlador de substituição (localizados em etiquetas no controlador).
.. Peça ao administrador da rede que atualize as definições de endereço IP do controlador original para refletir os endereços MAC do controlador de substituição.
+

CAUTION: Você deve garantir que os endereços IP do controlador original foram atualizados antes de aplicar energia ao controlador de substituição. Caso contrário, o controlador obterá novos endereços IP DHCP quando iniciar e poderá não conseguir reconetar-se ao StorageGRID. Esta etapa se aplica a todas as redes StorageGRID conetadas ao controlador.



. Retire o controlador do aparelho:
+
.. Coloque uma pulseira antiestática ou tome outras precauções antiestáticas.
.. Identifique os cabos e, em seguida, desligue os cabos e SFPs.
+

NOTE: Para evitar um desempenho degradado, não torça, dobre, aperte ou pise nos cabos.

.. Solte o controlador do aparelho apertando o trinco na pega do came até soltar e, em seguida, abra a pega do came para a direita.
.. Utilizando as duas mãos e a pega do came, deslize o controlador para fora do aparelho.
+

CAUTION: Utilize sempre duas mãos para suportar o peso do controlador.



. Instale o controlador de substituição no aparelho.
+
.. Vire o controlador ao contrário, de modo a que a tampa amovível fique virada para baixo.
.. Com a pega do came na posição aberta, deslize o controlador até ao aparelho.
.. Mova a alavanca do came para a esquerda para bloquear o controlador no lugar.
.. Substitua os cabos e SFPs.


. Ligue o aparelho e monitorize os LEDs do controlador e os ecrãs de sete segmentos.
+
Depois que os controladores iniciarem com êxito, os visores de sete segmentos devem mostrar o seguinte:

+
** Controlador da série E2800:
+
O estado final é `99`.

** Controlador E5700SG:
+
O estado final é `HA`.



. Confirme se o nó de armazenamento do dispositivo é exibido no Gerenciador de Grade e se nenhum alarme é exibido.


Após a substituição da peça, devolva a peça com falha à NetApp, conforme descrito nas instruções de RMA fornecidas com o kit. Consulte a https://mysupport.netapp.com/site/info/rma["Substituição  Devolução artigo"^] página para obter mais informações.

.Informações relacionadas
https://docs.netapp.com/us-en/e-series-family/index.html["Documentação do NetApp e-Series"^]
