---
permalink: sg5800/index.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Mantenha o aparelho SG5800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Talvez seja necessário atualizar o software SANtricity os na controladora E4000, alterar a configuração do link Ethernet da controladora SG5800, substituir a controladora E4000 ou a controladora SG5800 ou substituir componentes específicos. Os procedimentos nesta seção pressupõem que o dispositivo já foi implantado como nó de storage em um sistema StorageGRID.

Os procedimentos específicos para a manutenção do seu aparelho SG5800 estão nesta secção.

link:../commonhardware/index.html["Procedimentos comuns"]Consulte para obter os procedimentos de manutenção utilizados por todos os aparelhos.

Consulte link:../installconfig/configuring-hardware.html["Configure o hardware"] para obter informações sobre os procedimentos de manutenção que também são realizados durante a instalação e configuração iniciais do aparelho.
