---
permalink: commonhardware/how-appliance-node-cloning-works.html 
sidebar: sidebar 
keywords: storagegrid, appliance node cloning, appliance node clone 
summary: Você pode clonar um nó de dispositivo no StorageGRID para usar um dispositivo de design mais recente ou recursos aprimorados. A clonagem transfere todas as informações sobre o nó existente para o novo dispositivo, fornece um processo de atualização de hardware fácil de executar e fornece uma alternativa à desativação e expansão para a substituição de dispositivos. 
---
= Como funciona a clonagem de nós de dispositivos StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode clonar um nó de dispositivo no StorageGRID para usar um dispositivo de design mais recente ou recursos aprimorados. A clonagem transfere todas as informações sobre o nó existente para o novo dispositivo, fornece um processo de atualização de hardware fácil de executar e fornece uma alternativa à desativação e expansão para a substituição de dispositivos.

A clonagem do nó do dispositivo permite substituir facilmente um nó do dispositivo (origem) existente na grade por um dispositivo compatível (destino) que faz parte do mesmo local lógico da StorageGRID. O processo transfere todos os dados para o novo dispositivo, colocando-os em serviço para substituir o nó antigo do dispositivo e deixando o dispositivo antigo em um estado de pré-instalação.



[[why-clone-an-appliance-node]]
== Por que clonar um nó de dispositivo?

Você pode clonar um nó de dispositivo se precisar:

* Substitua os aparelhos que estão chegando ao fim da vida útil.
* Atualize os nós existentes para aproveitar a tecnologia aprimorada do dispositivo.
* Aumente a capacidade de storage em grade sem alterar o número de nós de storage no sistema StorageGRID.
* Aumentar a eficiência de storage, como alterar o modo RAID de DDP-8 para DDP-16 ou RAID-6.
* Implemente com eficiência a criptografia de nó para permitir o uso de servidores de gerenciamento de chaves externas (KMS).




[[which-storagegrid-network-is-used]]
== Que rede StorageGRID é utilizada?

A clonagem transfere dados do nó de origem diretamente para o dispositivo de destino em qualquer uma das três redes StorageGRID. Normalmente, a rede de Grade é utilizada, mas também pode utilizar a rede Admin ou a rede Cliente se o utilitário de origem estiver ligado a estas redes. Escolha a rede a ser usada para clonagem de tráfego que forneça a melhor performance de transferência de dados sem prejudicar a performance da rede StorageGRID ou a disponibilidade de dados.

Ao instalar o dispositivo de substituição, você deve especificar endereços IP temporários para conexão StorageGRID e transferência de dados. Como o dispositivo de substituição fará parte das mesmas redes que o nó do dispositivo que ele substitui, você deve especificar endereços IP temporários para cada uma dessas redes no dispositivo de substituição.



[[what-information-is-not-cloned]]
== Que informação não é clonada?

As configurações do dispositivo a seguir não são transferidas para o dispositivo de substituição durante a clonagem. Deve configurá-los durante a configuração inicial do aparelho de substituição.

* Interface BMC
* Ligações de rede
* Status da criptografia do nó
* Gerenciador de sistema do SANtricity (para nós de storage)
* Modo RAID (para nós de storage)




[[what-issues-prevent-cloning]]
== Que problemas impedem a clonagem?

Se algum dos seguintes problemas for encontrado durante a clonagem, o processo de clonagem será interrompido e uma mensagem de erro será gerada:

* Clonagem já em andamento
* Configuração de rede incorreta
* O appliance de destino não consegue alcançar o nó de administração primário
* Falta de conetividade entre os dispositivos de origem e destino
* Os dispositivos de origem e destino não são compatíveis
* Os dispositivos de origem e destino estão em estados de modo de manutenção diferentes
* As versões do instalador do StorageGRID Appliance nos dispositivos de origem e de destino não correspondem
* Para Storage Nodes, o appliance de destino possui armazenamento incompatível ou capacidade insuficiente
* O appliance Target não está pronto


Para continuar, é necessário resolver cada problema de clonagem.



[[target-appliance-compatibility]]
== Compatibilidade do dispositivo alvo

Os dispositivos de substituição devem ser do mesmo tipo que o nó de origem que estão substituindo e ambos devem fazer parte do mesmo local lógico do StorageGRID.

Reveja as considerações gerais de clonagem e as informações e restrições específicas de clonagem para cada tipo de dispositivo antes da clonagem.



[[general-services-appliance-cloning-considerations]]
=== Considerações gerais sobre clonagem de dispositivos de serviços

* Um dispositivo de serviços de substituição pode ser um modelo diferente do nó de administração ou do nó de gateway que está substituindo.
* Os aparelhos de serviços têm conetores de rede diferentes. Mudar o tipo de aparelho pode exigir a substituição dos cabos ou módulos SFP.




[[general-storage-appliance-cloning-considerations]]
=== Considerações gerais sobre a clonagem de dispositivos de storage

* Um dispositivo de storage de substituição deve ter maior capacidade do que o nó de storage que está substituindo.
+
** Se o dispositivo de armazenamento de destino tiver o mesmo número de unidades que o nó de origem, as unidades no dispositivo de destino devem ter maior capacidade (em TB).
** Se você planeja usar o mesmo modo RAID no nó de destino que foi usado no nó de origem ou um modo RAID com menos eficiência de armazenamento (por exemplo, alternar de RAID 6 para DDP), as unidades no dispositivo de destino devem ser maiores (em TB) do que as unidades no dispositivo de origem.
** O número de volumes em um dispositivo de storage de destino deve ser maior ou igual ao número de volumes no nó de origem. O SGF6112 possui 12 volumes e o SGF6212 possui 13 volumes. Todos os outros dispositivos de storage possuem 16 volumes.
** As exceções às considerações gerais de clonagem de dispositivos de storage incluem:
+
*** Se o número de unidades padrão instaladas em um dispositivo de armazenamento de destino for menor que o número de unidades no nó de origem, devido à instalação de unidades de estado sólido (SSDs), a capacidade geral de armazenamento das unidades padrão no dispositivo de destino (em TB) deve exceder a capacidade total da unidade funcional de todas as unidades no nó de armazenamento de origem.
+
Por exemplo, ao clonar um dispositivo de nó de storage de SG5760 fontes com 60 unidades para um dispositivo de destino de SG6060 U com 58 unidades padrão, unidades maiores devem ser instaladas no dispositivo de destino SG6060 antes da clonagem para manter a capacidade de storage. (Os dois slots de unidade que contêm SSDs no dispositivo de destino não estão incluídos na capacidade total de armazenamento do dispositivo.)

+
No entanto, se um dispositivo de nó de origem de SG5760 unidades de 60 unidades estiver configurado com SANtricity Dynamic Disk Pools DDP-8 (DDP), configurar um dispositivo de destino de SG6060 unidades com mesmo tamanho de 58 unidades com DDP-16 pode tornar o dispositivo SG6060 um destino de clone válido devido à sua eficiência de storage aprimorada.

+
Você pode visualizar informações sobre o modo RAID atual do nó do dispositivo de origem na página *Nós* do Grid Manager. Selecione a guia *Armazenamento* do dispositivo.

*** Não é possível clonar um nó de origem com 16 volumes de armazenamento de objetos (rangedb) para um dispositivo de storage de destino com menos volumes de armazenamento de objetos, mesmo que o dispositivo de destino tenha maior capacidade do que o nó de origem.








[[sg100-appliance-cloning-information-and-restrictions]]
=== SG100 informações e restrições sobre clonagem de dispositivos

Você pode clonar um dispositivo de nó de origem SG100 para um dispositivo de destino de serviços SG110, SG1000 ou SG1100. Clonar o SG100 para um dispositivo de destino de serviços SG1000 ou SG1100 oferece ao nó de administrador ou nó de gateway maior capacidade.



[[sg110-appliance-cloning-information-and-restrictions]]
=== SG110 informações e restrições sobre clonagem de dispositivos

Você pode clonar um dispositivo de nó de origem SG110 para um destino de dispositivo de serviços SG1100 para oferecer maior capacidade ao nó de administrador ou nó de gateway.

A clonagem de nós não é suportada de um dispositivo de nó de origem SG110 sem criptografia de nó para um dispositivo de destino SG110 com criptografia de nó.



[[sg120-appliance-cloning-information-and-restrictions]]
=== Informações e restrições sobre a clonagem do dispositivo SG120

Você pode clonar um dispositivo de nó de origem SG120 para um dispositivo de serviços SG1200 como destino, a fim de proporcionar maior capacidade ao Nó de Administração ou ao Nó de Gateway.

A clonagem de nó não é suportada de um dispositivo de nó SG120 de origem sem criptografia de nó para um dispositivo SG120 de destino com criptografia de nó.



[[sg1000-appliance-cloning-information-and-restrictions]]
=== SG1000 informações e restrições sobre clonagem de dispositivos

Você pode clonar um dispositivo de nó de origem SG1000 para um dispositivo de destino de serviços SG100, SG110 ou SG1100.

* Clonar o SG1000 para um dispositivo de destino de serviços SG100 ou SG110 permite que você reimplante o SG1000 para uma aplicação mais exigente.
* A substituição de um dispositivo de nó de origem SG1000 por um dispositivo de destino de serviços SG100 reduz a velocidade máxima das portas de rede de 100 GbE para 25 GbE.




[[sg1100-appliance-cloning-information-and-restrictions]]
=== SG1100 informações e restrições sobre clonagem de dispositivos

Você pode clonar um dispositivo de nó de origem SG1100 para um dispositivo de destino de serviços SG110.

* Clonar o SG1100 para um dispositivo de destino de serviços SG110 permite que você reimplante o SG1100 para uma aplicação mais exigente. Por exemplo, se um dispositivo de nó de origem SG1100 estiver sendo usado como nó Admin e você quiser usá-lo como um nó de balanceamento de carga dedicado.
* A substituição de um dispositivo de nó de origem SG1100 por um dispositivo de destino de serviços SG110 reduz a velocidade máxima das portas de rede de 100 GbE para 25 GbE.


A clonagem de nós não é suportada de um dispositivo de nó de origem SG1100 sem criptografia de nó para um dispositivo de destino SG1100 com criptografia de nó.



[[sg1200-appliance-cloning-information-and-restrictions]]
=== Informações e restrições sobre a clonagem do dispositivo SG1200

Você pode clonar um dispositivo de nó de origem SG1200 para um dispositivo de destino de serviços SG1200.

* Clonar o SG1200 para um dispositivo de destino de serviços SG120 permite que você reimplemente o SG1200 para uma aplicação mais exigente. Por exemplo, se um dispositivo de nó de origem SG1200 estiver sendo usado como um nó de administração e você quiser usá-lo como um nó de balanceamento de carga dedicado.
* A substituição de um dispositivo de nó de origem SG1200 por um dispositivo de destino de serviços SG120 reduz a velocidade máxima das portas de rede de 100-GbE para 25-GbE.


A clonagem de nó não é suportada de um dispositivo de nó SG1200 de origem sem criptografia de nó para um dispositivo SG1200 de destino com criptografia de nó.



[[sg5712-appliance-cloning-information-and-restrictions]]
=== SG5712 informações e restrições sobre clonagem de dispositivos

Você pode clonar um dispositivo de nó de SG5712 origem configurado com DDP para um dispositivo de destino de storage SG5812.



[[sg5760-appliance-cloning-information-and-restrictions]]
=== SG5760 informações e restrições sobre clonagem de dispositivos

* Você pode clonar um dispositivo de nó de origem SG5760 configurado com DDP16 para um dispositivo de destino de storage SG5860 configurado com DDP16.
* Um dispositivo de nó de origem SG5760 configurado com DDP _não pode_ ser clonado para um dispositivo de destino de storage SG5860 configurado com DDP.
* Um dispositivo de nó de origem SG5760 configurado com DDP ou DDP-16 _não pode_ ser clonado para um dispositivo de storage de destino SG6160 ou SG6260 com um modo RAID correspondente.




[[sg5812-appliance-cloning-information-and-restrictions]]
=== SG5812 informações e restrições sobre clonagem de dispositivos

Você pode clonar com sucesso um dispositivo SG5812 como a origem ou o destino.



[[sg5860-appliance-cloning-information-and-restrictions]]
=== SG5860 informações e restrições sobre clonagem de dispositivos

Você pode clonar com sucesso um dispositivo SG5860 como a origem ou o destino com algumas restrições (listadas nas informações de clonagem do dispositivo e restrições para cada fonte).



[[sg6060-appliance-cloning-information-and-restrictions]]
=== SG6060 informações e restrições sobre clonagem de dispositivos

* Você pode clonar um dispositivo de nó de origem SG6060 configurado com DDP ou DDP16 para um dispositivo de destino de storage SG5860 com um modo RAID correspondente.
* É possível clonar um dispositivo de origem SG6060 sem gavetas de expansão para um dispositivo de storage SG6160 ou SG6260 também sem gavetas de expansão, desde que os tamanhos dos discos e os modos RAID sejam os mesmos.
* Um dispositivo de nó de origem SG6060 com qualquer número de gavetas de expansão _não pode_ ser clonado para um dispositivo de storage de destino SG6160 ou SG6260, mesmo que o número de gavetas de expansão, tamanhos de disco e modos RAID sejam os mesmos.




[[sgf6112-appliance-cloning-information-and-restrictions]]
=== Informações e restrições sobre clonagem de dispositivos SGF6112

Clonagem de nó não é suportada de um dispositivo de origem SGF6112 sem criptografia de nó para um dispositivo de destino SGF6112 ou SGF6212 com criptografia de nó.



[[sg6160-and-sg6260-appliance-cloning-information-and-restrictions]]
=== Informações e restrições sobre a clonagem dos dispositivos SG6160 e SG6260

Você pode clonar com sucesso um dispositivo SG6160 como a origem ou o destino com algumas restrições (listadas nas informações de clonagem do dispositivo e restrições para cada fonte).
